---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
      version: v79.7.1
  interval: 1m0s
  # Values to make Prometheus Operator discover ServiceMonitor/PodMonitor from application namespaces
  # and configure Grafana with Prometheus as default datasource
  values:
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        # allow Prometheus to discover ServiceMonitors from other namespaces
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        # allow Prometheus to discover PodMonitors from other namespaces
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}
        # allow PrometheusRules from other namespaces (optional)
        ruleSelector: {}
        ruleNamespaceSelector: {}
    grafana:
      # Enable Grafana (included in kube-prometheus-stack)
      enabled: true
      # Configure default datasources
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-release-kube-pr-prometheus:9090
            access: proxy
            isDefault: true
      # Configure Grafana ingress
      ingress:
        enabled: true
        ingressClassName: nginx
        path: /
        pathType: Prefix
        hosts:
          - grafana.local
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
