---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx-repo
  namespace: ingress-nginx
spec:
  interval: 10m0s
  url: https://kubernetes.github.io/ingress-nginx
