apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: service-example
  namespace: service-example
resources:
- namespace.yaml
- mongodb-credentials-sealedsecret.yaml
- redis-credentials-sealedsecret.yaml
- nats-credentials-sealedsecret.yaml
- helm-repo.yaml
- helm-release.yaml