name: Test, Build & Push ServiceExample application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone ServiceExample repo
        run: |
          git clone https://github.com/vvitkovsky/ServiceExample.git service-example-ext

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Test service-example
        run: |
          cd service-example-ext
          dotnet test --no-build --verbosity normal

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ./service-example-ext
          file: ./service-example-ext/ServiceExample/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/serviceexample:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/serviceexample:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/serviceexample:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/serviceexample:cache,mode=max
